# Generated by Django 5.1.7 on 2025-03-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('ruido', 'Ruido'), ('seguridad', 'Seguridad'), ('limpieza', 'Limpieza'), ('areas_comunes', 'Areas comunes'), ('recepcion', 'Recepcion'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
