# Generated by Django 5.1.7 on 2025-03-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('ruido', 'Ruido'), ('seguridad', 'Seguridad'), ('limpieza', 'Limpieza'), ('areas_comunes', 'Áreas comunes'), ('recepcion', 'Recepcion'), ('mascotas', 'Mascotas'), ('desastres_naturales', 'Desastres Naturales'), ('olores', 'Olores Desagradables'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
